environment:
  matrix:
    - nodejs_version: "14"
install:
  - npm i
before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=9rEhCCz4_rUf0wwPCvrdd8uVWrxZ4fSW
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb testdb
services:
  - postgresql101
test_script:
  - npm test
build: off
